version = 1

test_patterns = ["**.test.js"]

exclude_patterns = [
  "packages/docs/**",
  "**/public/**",
  "**/dist/**"
]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  module_system = "es-modules"
  dependency_file_paths = [
    "packages/ajv/package.json",
    "packages/api/package.json",
    "packages/blocks/blocksAntd/package.json",
    "packages/blocks/blocksBasic/package.json",
    "packages/blocks/blocksColorSelectors/package.json",
    "packages/blocks/blocksECharts/package.json",
    "packages/blocks/blocksMarkdown/package.json",
    "packages/blockDev/package.json",
    "packages/blockTools/package.json",
    "packages/build/package.json",
    "packages/cli/package.json",
    "packages/client/package.json",
    "packages/color/package.json",
    "packages/engine/package.json",
    "packages/format/package.json",
    "packages/graphql/package.json",
    "packages/graphql-federated/package.json",
    "packages/helpers/package.json",
    "packages/layout/package.json",
    "packages/nodeUtils/package.json",
    "packages/nunjucks/package.json",
    "packages/operators/package.json",
    "packages/server/package.json",
    "packages/servers/package.json",
    "packages/shell/package.json",
    "package.json"
  ]
  environment = ["nodejs","browser","jest"]
