# Copyright 2020-2024 Lowdefy, Inc

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_ref:
  path: templates/general.yaml.njk
  vars:
    pageId: auth-configuration
    pageTitle: Auth Configuration
    section: User Authentication
    filePath: users/auth-configuration.yaml
    content:
      - id: auth_configuration
        type: MarkdownWithCode
        properties:
          content:
            _nunjucks:
              on:
                version:
                  _ref: version.yaml
              template: |
                The `auth` section of the Lowdefy configuration is used to configure the user authentication settings.

                The `_secret` operator is evaluated over the entire section.

                ## User Fields

                The `auth.userFields` section of the auth config is used to configure which data fields from the provider are mapped to the `user` data object. NextAuth provides three data objects from which data can read, namely `account`, `profile` and `user`. The content of these objects depends on the provider that was used.

                See [User Object](/user-object) and [Next-Auth JWT Callback](https://next-auth.js.org/configuration/callbacks#jwt-callback) for more details.

                ## Theme

                The `auth.theme` section maps to the [NextAuth theme options](https://next-auth.js.org/configuration/options#theme).

                The options are:
                - `colorScheme: enum`: Sets the color scheme of the Next-Auth auth pages. Options are `"auto"`, `"dark"` and `"light"`. The default is `"auto"`.
                - `brandColor: string`: A hex color code of the color to use as accent color on the Next-Auth auth pages.
                - `logo: string`: The absolute URL of an image to be used as logo on the auth pages.
                - `buttonText: string`: A hex color code of the color to use for button text.

                ## Auth Pages

                The `auth.authPages` section can be used to override the auth pages provided by NextAuth. The values should link to pages inside the Lowdefy app.

                See [here](https://next-auth.js.org/configuration/pages) for more details.

                The options are:
                - `signIn: string`
                - `signOut: string`
                - `error: string`
                - `verifyRequest: string`: Used for check email message.
                - `newUser: string`: New users will be directed here on first sign in (leave the property out if not of interest)

                ###### Configure a custom sign-in page
                ```yaml
                lowdefy: {{ version }}

                auth:
                  authPages:
                    signIn: /login
                ```

                ## Session

                The `auth.session` config maps to the [NextAuth session](https://next-auth.js.org/configuration/options#session) config option. It can be used to set the maximum session length using the `auth.session.maxAge` option.

                ###### Set a maximum session length of twelve hours
                ```yaml
                lowdefy: {{ version }}

                auth:
                  session:
                    maxAge: 43200 # 12 hours in seconds
                ```

                ## Debug

                If the server log level is set to `debug`, the Next-Auth debug mode will be enabled. The `auth.debug` property can be set to false to disable authentication debug output.

                ## Cookies

                The  `auth.advanced.cookies` section can be used to overwrite the NextAuth cookie options. This is an advanced option and using it is not recommended as you may break authentication or introduce security flaws into your application. See [here](https://next-auth.js.org/configuration/options#cookies) for more details.

      - _ref:
          path: templates/navigation_buttons.yaml
          vars:
            previous_page_title: User Object
            previous_page_id: user-object
            next_page_title: Login and Logout
            next_page_id: login-and-logout
